title: Business Ideas Philippines
author: Kevin Olega
email: kevinolegaservices@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Turn your ideas into reality

twitter_username: kevinolega
github_username:  kevinolega

sass:
    style: compressed